/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 89
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 87
#define ALIAS_COUNT 0
#define TOKEN_COUNT 62
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 15
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_file_token1 = 1,
  anon_sym_COLON_COLON = 2,
  aux_sym_passage_header_token1 = 3,
  sym_passage_name = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  sym_tag = 7,
  anon_sym_LBRACE = 8,
  aux_sym_metadata_token1 = 9,
  anon_sym_RBRACE = 10,
  aux_sym__passage_content_token1 = 11,
  aux_sym__passage_content_token2 = 12,
  aux_sym__passage_content_token3 = 13,
  aux_sym__passage_content_token4 = 14,
  sym_html_tag = 15,
  anon_sym_LT_LT = 16,
  anon_sym_GT_GT = 17,
  anon_sym_LT_LT_SLASH = 18,
  anon_sym_end = 19,
  anon_sym_LT_LTscript_GT_GT = 20,
  anon_sym_LT_LT_SLASHscript_GT_GT = 21,
  sym_macro_name = 22,
  aux_sym__macro_arg_token_token1 = 23,
  aux_sym__macro_arg_token_token2 = 24,
  aux_sym__macro_arg_token_token3 = 25,
  aux_sym__macro_arg_token_token4 = 26,
  aux_sym__macro_arg_token_token5 = 27,
  aux_sym__macro_arg_token_token6 = 28,
  sym_variable = 29,
  sym_temp_variable = 30,
  anon_sym_AT_AT = 31,
  aux_sym_styled_text_token1 = 32,
  anon_sym_SEMI = 33,
  aux_sym_styled_text_token2 = 34,
  anon_sym_LBRACK_LBRACK = 35,
  anon_sym_PIPE = 36,
  anon_sym_RBRACK_RBRACK = 37,
  sym_link_text = 38,
  anon_sym_LBRACKimg_LBRACK = 39,
  aux_sym_image_link_token1 = 40,
  anon_sym_DQUOTE = 41,
  aux_sym_string_literal_token1 = 42,
  anon_sym_SQUOTE = 43,
  aux_sym_string_literal_token2 = 44,
  anon_sym_BQUOTE = 45,
  aux_sym_string_literal_token3 = 46,
  sym_number_literal = 47,
  anon_sym_true = 48,
  anon_sym_false = 49,
  anon_sym_LT_LT_EQ = 50,
  aux_sym_naked_expression_token1 = 51,
  anon_sym_SLASH_STAR = 52,
  anon_sym_STAR_SLASH = 53,
  anon_sym_LT_BANG_DASH_DASH = 54,
  anon_sym_DASH_DASH_GT = 55,
  sym_text = 56,
  sym__raw_js_body = 57,
  sym__raw_html_comment = 58,
  sym__sc_comment_body = 59,
  sym__error_sentinel = 60,
  sym__raw_passage_body = 61,
  sym_source_file = 62,
  sym_passage = 63,
  sym_passage_header = 64,
  sym_tag_list = 65,
  sym_metadata = 66,
  sym_passage_body = 67,
  sym__passage_content = 68,
  sym_macro = 69,
  sym_end_macro = 70,
  sym_script_block = 71,
  sym_macro_args = 72,
  sym__macro_arg_token = 73,
  sym_styled_text = 74,
  sym_wiki_link = 75,
  sym_image_link = 76,
  sym_string_literal = 77,
  sym_bool_literal = 78,
  sym_naked_expression = 79,
  sym_sc_comment = 80,
  sym_html_comment = 81,
  aux_sym_source_file_repeat1 = 82,
  aux_sym_source_file_repeat2 = 83,
  aux_sym_tag_list_repeat1 = 84,
  aux_sym_passage_body_repeat1 = 85,
  aux_sym_macro_args_repeat1 = 86,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_file_token1] = "source_file_token1",
  [anon_sym_COLON_COLON] = "::",
  [aux_sym_passage_header_token1] = "passage_header_token1",
  [sym_passage_name] = "passage_name",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_tag] = "tag",
  [anon_sym_LBRACE] = "{",
  [aux_sym_metadata_token1] = "metadata_token1",
  [anon_sym_RBRACE] = "}",
  [aux_sym__passage_content_token1] = "_passage_content_token1",
  [aux_sym__passage_content_token2] = "_passage_content_token2",
  [aux_sym__passage_content_token3] = "_passage_content_token3",
  [aux_sym__passage_content_token4] = "_passage_content_token4",
  [sym_html_tag] = "html_tag",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LT_LT_SLASH] = "<</",
  [anon_sym_end] = "end",
  [anon_sym_LT_LTscript_GT_GT] = "<<script>>",
  [anon_sym_LT_LT_SLASHscript_GT_GT] = "<</script>>",
  [sym_macro_name] = "macro_name",
  [aux_sym__macro_arg_token_token1] = "_macro_arg_token_token1",
  [aux_sym__macro_arg_token_token2] = "_macro_arg_token_token2",
  [aux_sym__macro_arg_token_token3] = "_macro_arg_token_token3",
  [aux_sym__macro_arg_token_token4] = "_macro_arg_token_token4",
  [aux_sym__macro_arg_token_token5] = "_macro_arg_token_token5",
  [aux_sym__macro_arg_token_token6] = "_macro_arg_token_token6",
  [sym_variable] = "variable",
  [sym_temp_variable] = "temp_variable",
  [anon_sym_AT_AT] = "@@",
  [aux_sym_styled_text_token1] = "styled_text_token1",
  [anon_sym_SEMI] = ";",
  [aux_sym_styled_text_token2] = "styled_text_token2",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_PIPE] = "|",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [sym_link_text] = "link_text",
  [anon_sym_LBRACKimg_LBRACK] = "[img[",
  [aux_sym_image_link_token1] = "image_link_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_string_literal_token3] = "string_literal_token3",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LT_LT_EQ] = "<<=",
  [aux_sym_naked_expression_token1] = "expression",
  [anon_sym_SLASH_STAR] = "/*",
  [anon_sym_STAR_SLASH] = "*/",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_text] = "text",
  [sym__raw_js_body] = "raw_content",
  [sym__raw_html_comment] = "_raw_html_comment",
  [sym__sc_comment_body] = "_sc_comment_body",
  [sym__error_sentinel] = "_error_sentinel",
  [sym__raw_passage_body] = "_raw_passage_body",
  [sym_source_file] = "source_file",
  [sym_passage] = "passage",
  [sym_passage_header] = "passage_header",
  [sym_tag_list] = "tag_list",
  [sym_metadata] = "metadata",
  [sym_passage_body] = "passage_body",
  [sym__passage_content] = "_passage_content",
  [sym_macro] = "macro",
  [sym_end_macro] = "end_macro",
  [sym_script_block] = "script_block",
  [sym_macro_args] = "macro_args",
  [sym__macro_arg_token] = "_macro_arg_token",
  [sym_styled_text] = "styled_text",
  [sym_wiki_link] = "wiki_link",
  [sym_image_link] = "image_link",
  [sym_string_literal] = "string_literal",
  [sym_bool_literal] = "bool_literal",
  [sym_naked_expression] = "naked_expression",
  [sym_sc_comment] = "sc_comment",
  [sym_html_comment] = "html_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_tag_list_repeat1] = "tag_list_repeat1",
  [aux_sym_passage_body_repeat1] = "passage_body_repeat1",
  [aux_sym_macro_args_repeat1] = "macro_args_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [aux_sym_passage_header_token1] = aux_sym_passage_header_token1,
  [sym_passage_name] = sym_passage_name,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_tag] = sym_tag,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_metadata_token1] = aux_sym_metadata_token1,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__passage_content_token1] = aux_sym__passage_content_token1,
  [aux_sym__passage_content_token2] = aux_sym__passage_content_token2,
  [aux_sym__passage_content_token3] = aux_sym__passage_content_token3,
  [aux_sym__passage_content_token4] = aux_sym__passage_content_token4,
  [sym_html_tag] = sym_html_tag,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LT_LT_SLASH] = anon_sym_LT_LT_SLASH,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_LT_LTscript_GT_GT] = anon_sym_LT_LTscript_GT_GT,
  [anon_sym_LT_LT_SLASHscript_GT_GT] = anon_sym_LT_LT_SLASHscript_GT_GT,
  [sym_macro_name] = sym_macro_name,
  [aux_sym__macro_arg_token_token1] = aux_sym__macro_arg_token_token1,
  [aux_sym__macro_arg_token_token2] = aux_sym__macro_arg_token_token2,
  [aux_sym__macro_arg_token_token3] = aux_sym__macro_arg_token_token3,
  [aux_sym__macro_arg_token_token4] = aux_sym__macro_arg_token_token4,
  [aux_sym__macro_arg_token_token5] = aux_sym__macro_arg_token_token5,
  [aux_sym__macro_arg_token_token6] = aux_sym__macro_arg_token_token6,
  [sym_variable] = sym_variable,
  [sym_temp_variable] = sym_temp_variable,
  [anon_sym_AT_AT] = anon_sym_AT_AT,
  [aux_sym_styled_text_token1] = aux_sym_styled_text_token1,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [aux_sym_styled_text_token2] = aux_sym_styled_text_token2,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [sym_link_text] = sym_link_text,
  [anon_sym_LBRACKimg_LBRACK] = anon_sym_LBRACKimg_LBRACK,
  [aux_sym_image_link_token1] = aux_sym_image_link_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_string_literal_token3] = aux_sym_string_literal_token3,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LT_LT_EQ] = anon_sym_LT_LT_EQ,
  [aux_sym_naked_expression_token1] = aux_sym_naked_expression_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_text] = sym_text,
  [sym__raw_js_body] = sym__raw_js_body,
  [sym__raw_html_comment] = sym__raw_html_comment,
  [sym__sc_comment_body] = sym__sc_comment_body,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym__raw_passage_body] = sym__raw_passage_body,
  [sym_source_file] = sym_source_file,
  [sym_passage] = sym_passage,
  [sym_passage_header] = sym_passage_header,
  [sym_tag_list] = sym_tag_list,
  [sym_metadata] = sym_metadata,
  [sym_passage_body] = sym_passage_body,
  [sym__passage_content] = sym__passage_content,
  [sym_macro] = sym_macro,
  [sym_end_macro] = sym_end_macro,
  [sym_script_block] = sym_script_block,
  [sym_macro_args] = sym_macro_args,
  [sym__macro_arg_token] = sym__macro_arg_token,
  [sym_styled_text] = sym_styled_text,
  [sym_wiki_link] = sym_wiki_link,
  [sym_image_link] = sym_image_link,
  [sym_string_literal] = sym_string_literal,
  [sym_bool_literal] = sym_bool_literal,
  [sym_naked_expression] = sym_naked_expression,
  [sym_sc_comment] = sym_sc_comment,
  [sym_html_comment] = sym_html_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_tag_list_repeat1] = aux_sym_tag_list_repeat1,
  [aux_sym_passage_body_repeat1] = aux_sym_passage_body_repeat1,
  [aux_sym_macro_args_repeat1] = aux_sym_macro_args_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_passage_header_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_passage_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_metadata_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__passage_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__passage_content_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__passage_content_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__passage_content_token4] = {
    .visible = false,
    .named = false,
  },
  [sym_html_tag] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LTscript_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT_SLASHscript_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__macro_arg_token_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__macro_arg_token_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__macro_arg_token_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__macro_arg_token_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__macro_arg_token_token5] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__macro_arg_token_token6] = {
    .visible = false,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_temp_variable] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_styled_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_styled_text_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_link_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACKimg_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_image_link_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_naked_expression_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__raw_js_body] = {
    .visible = true,
    .named = true,
  },
  [sym__raw_html_comment] = {
    .visible = false,
    .named = true,
  },
  [sym__sc_comment_body] = {
    .visible = false,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym__raw_passage_body] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_passage] = {
    .visible = true,
    .named = true,
  },
  [sym_passage_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_list] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_passage_body] = {
    .visible = true,
    .named = true,
  },
  [sym__passage_content] = {
    .visible = false,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_end_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_script_block] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_args] = {
    .visible = true,
    .named = true,
  },
  [sym__macro_arg_token] = {
    .visible = false,
    .named = true,
  },
  [sym_styled_text] = {
    .visible = true,
    .named = true,
  },
  [sym_wiki_link] = {
    .visible = true,
    .named = true,
  },
  [sym_image_link] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_naked_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_sc_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_html_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_passage_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_args_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_code = 2,
  field_content = 3,
  field_expression = 4,
  field_label = 5,
  field_metadata = 6,
  field_name = 7,
  field_style = 8,
  field_tags = 9,
  field_target = 10,
  field_url = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_code] = "code",
  [field_content] = "content",
  [field_expression] = "expression",
  [field_label] = "label",
  [field_metadata] = "metadata",
  [field_name] = "name",
  [field_style] = "style",
  [field_tags] = "tags",
  [field_target] = "target",
  [field_url] = "url",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 1},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 10, .length = 3},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 2},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 2},
  [14] = {.index = 20, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 1},
    {field_tags, 2},
  [3] =
    {field_metadata, 2},
    {field_name, 1},
  [5] =
    {field_code, 1},
  [6] =
    {field_content, 1},
  [7] =
    {field_target, 1},
  [8] =
    {field_url, 1},
  [9] =
    {field_expression, 1},
  [10] =
    {field_metadata, 3},
    {field_name, 1},
    {field_tags, 2},
  [13] =
    {field_name, 2},
  [14] =
    {field_args, 2},
    {field_name, 1},
  [16] =
    {field_content, 3},
    {field_style, 1},
  [18] =
    {field_label, 1},
    {field_target, 3},
  [20] =
    {field_target, 4},
    {field_url, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 19,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 60,
  [87] = 56,
  [88] = 88,
};

static const TSCharacterRange aux_sym__macro_arg_token_token5_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '#'}, {'%', '&'}, {'(', ';'}, {'=', '='}, {'?', '^'},
  {'`', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(60);
      ADVANCE_MAP(
        '\n', 61,
        '"', 126,
        '$', 96,
        '\'', 129,
        '*', 7,
        '-', 5,
        '/', 3,
        ':', 9,
        ';', 115,
        '<', 75,
        '=', 13,
        '>', 78,
        '@', 80,
        '[', 67,
        ']', 69,
        '_', 92,
        '`', 132,
        'e', 34,
        'f', 23,
        't', 37,
        '{', 71,
        '|', 119,
        '}', 74,
        '(', 94,
        ')', 94,
      );
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 109,
        '"', 126,
        '$', 96,
        '\'', 129,
        '-', 106,
        '<', 76,
        '=', 97,
        '>', 78,
        '_', 92,
        '`', 132,
        'f', 98,
        't', 102,
        '(', 95,
        ')', 95,
        '\t', 108,
        '\r', 108,
        ' ', 108,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(107);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead == '[') ADVANCE(66);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == 'e') ADVANCE(90);
      if (lookahead == '{') ADVANCE(71);
      if (lookahead == '|') ADVANCE(119);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(143);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(145);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(144);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(41);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(62);
      END_STATE();
    case 10:
      if (lookahead == ';') ADVANCE(117);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(113);
      END_STATE();
    case 11:
      if (lookahead == '<') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(140);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(93);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(146);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(81);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '>') ADVANCE(87);
      END_STATE();
    case 17:
      if (lookahead == '>') ADVANCE(88);
      END_STATE();
    case 18:
      if (lookahead == '>') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == '[') ADVANCE(123);
      END_STATE();
    case 21:
      if (lookahead == ']') ADVANCE(69);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(70);
      END_STATE();
    case 22:
      if (lookahead == ']') ADVANCE(120);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(38);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 'd') ADVANCE(85);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(138);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(139);
      END_STATE();
    case 29:
      if (lookahead == 'g') ADVANCE(20);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == 'm') ADVANCE(29);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 35:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 36:
      if (lookahead == 'p') ADVANCE(43);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 45:
      if (lookahead == '{') ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 46:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(125);
      END_STATE();
    case 47:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(142);
      END_STATE();
    case 48:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(117);
      END_STATE();
    case 49:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(122);
      END_STATE();
    case 50:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(65);
      END_STATE();
    case 51:
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 53:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 54:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 55:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(128);
      END_STATE();
    case 56:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(134);
      END_STATE();
    case 57:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(131);
      END_STATE();
    case 58:
      if (eof) ADVANCE(60);
      ADVANCE_MAP(
        '\n', 61,
        '$', 45,
        '/', 149,
        ':', 150,
        '<', 75,
        '>', 77,
        '@', 80,
        '[', 151,
        '_', 54,
        '\t', 147,
        '\r', 147,
        ' ', 147,
      );
      if (lookahead != 0) ADVANCE(157);
      END_STATE();
    case 59:
      if (eof) ADVANCE(60);
      ADVANCE_MAP(
        '\n', 61,
        '$', 45,
        '/', 149,
        ':', 150,
        '<', 75,
        '>', 77,
        '@', 80,
        '[', 68,
        '_', 54,
        '\t', 148,
        '\r', 148,
        ' ', 148,
      );
      if (lookahead != 0) ADVANCE(157);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_passage_header_token1);
      if (lookahead == '\n') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_passage_name);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_passage_name);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(118);
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(118);
      if (lookahead == 'i') ADVANCE(154);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ']') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_metadata_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_metadata_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym__passage_content_token1);
      if (lookahead == '!') ADVANCE(6);
      if (lookahead == '/') ADVANCE(53);
      if (lookahead == '<') ADVANCE(82);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym__passage_content_token1);
      if (lookahead == '<') ADVANCE(12);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym__passage_content_token2);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym__passage_content_token2);
      if (lookahead == '>') ADVANCE(83);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym__passage_content_token3);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym__passage_content_token4);
      if (lookahead == '@') ADVANCE(112);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_html_tag);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      if (lookahead == '/') ADVANCE(84);
      if (lookahead == '=') ADVANCE(140);
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LT_LT_SLASH);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_end);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_end);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_LT_LTscript_GT_GT);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LT_LT_SLASHscript_GT_GT);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == 'd') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == 'n') ADVANCE(89);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token2);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token3);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token3);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token5);
      if (lookahead == '>') ADVANCE(93);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token5);
      if (lookahead == 'a') ADVANCE(101);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token5);
      if (lookahead == 'e') ADVANCE(138);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token5);
      if (lookahead == 'e') ADVANCE(139);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token5);
      if (lookahead == 'l') ADVANCE(103);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token5);
      if (lookahead == 'r') ADVANCE(104);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token5);
      if (lookahead == 's') ADVANCE(100);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token5);
      if (lookahead == 'u') ADVANCE(99);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token5);
      if ((!eof && set_contains(aux_sym__macro_arg_token_token5_character_set_1, 9, lookahead))) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token6);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym__macro_arg_token_token6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_temp_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_AT_AT);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_styled_text_token1);
      if (lookahead == ';') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_styled_text_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != ';' &&
          lookahead != '@') ADVANCE(113);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_styled_text_token2);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(117);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_styled_text_token2);
      if (lookahead != 0 &&
          lookahead != '@') ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_link_text);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(122);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_link_text);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(122);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_LBRACKimg_LBRACK);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym_image_link_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(125);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_image_link_token1);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\\') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(127);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(128);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\\') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead == '\\') ADVANCE(57);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(131);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      if (lookahead == '\\') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(131);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_string_literal_token3);
      if (lookahead == '\\') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(133);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(134);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(aux_sym_string_literal_token3);
      if (lookahead == '\\') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(134);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_LT_LT_EQ);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_naked_expression_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(142);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_naked_expression_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(142);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '\n', 61,
        '$', 155,
        '/', 149,
        ':', 150,
        '<', 75,
        '>', 77,
        '@', 80,
        '[', 151,
        '_', 156,
        '\t', 147,
        '\r', 147,
        ' ', 147,
      );
      if (lookahead != 0) ADVANCE(157);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '\n', 61,
        '$', 155,
        '/', 149,
        ':', 150,
        '<', 75,
        '>', 77,
        '@', 80,
        '[', 68,
        '_', 156,
        '\t', 148,
        '\r', 148,
        ' ', 148,
      );
      if (lookahead != 0) ADVANCE(157);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '*') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(157);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(157);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '[') ADVANCE(118);
      if (lookahead == 'i') ADVANCE(154);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(157);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '[') ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(157);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'g') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(157);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'm') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(157);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '{') ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          (lookahead < '@' || 'Z' < lookahead)) ADVANCE(157);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_text);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          (lookahead < '@' || 'Z' < lookahead)) ADVANCE(157);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '<' &&
          lookahead != '@') ADVANCE(157);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 58},
  [3] = {.lex_state = 58},
  [4] = {.lex_state = 58},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 59},
  [9] = {.lex_state = 58},
  [10] = {.lex_state = 58},
  [11] = {.lex_state = 58},
  [12] = {.lex_state = 58},
  [13] = {.lex_state = 58},
  [14] = {.lex_state = 58},
  [15] = {.lex_state = 58},
  [16] = {.lex_state = 58},
  [17] = {.lex_state = 58},
  [18] = {.lex_state = 58},
  [19] = {.lex_state = 58},
  [20] = {.lex_state = 58},
  [21] = {.lex_state = 58},
  [22] = {.lex_state = 58},
  [23] = {.lex_state = 58},
  [24] = {.lex_state = 58},
  [25] = {.lex_state = 58},
  [26] = {.lex_state = 58},
  [27] = {.lex_state = 58},
  [28] = {.lex_state = 58},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 21},
  [42] = {.lex_state = 21},
  [43] = {.lex_state = 21},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 2, .external_lex_state = 3},
  [47] = {.lex_state = 10},
  [48] = {.lex_state = 0, .external_lex_state = 4},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 46},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 47},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 48},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 49},
  [62] = {.lex_state = 50},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 49},
  [68] = {.lex_state = 127},
  [69] = {.lex_state = 133},
  [70] = {.lex_state = 51},
  [71] = {.lex_state = 72},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 130},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 49},
  [80] = {.lex_state = 51},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 47},
  [88] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_source_file_token1] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [aux_sym__passage_content_token1] = ACTIONS(1),
    [aux_sym__passage_content_token2] = ACTIONS(1),
    [aux_sym__passage_content_token4] = ACTIONS(1),
    [sym_html_tag] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LT_LT_SLASH] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_LT_LTscript_GT_GT] = ACTIONS(1),
    [aux_sym__macro_arg_token_token1] = ACTIONS(1),
    [aux_sym__macro_arg_token_token2] = ACTIONS(1),
    [aux_sym__macro_arg_token_token3] = ACTIONS(1),
    [aux_sym__macro_arg_token_token4] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_temp_variable] = ACTIONS(1),
    [anon_sym_AT_AT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LBRACKimg_LBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LT_LT_EQ] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(1),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [sym__raw_js_body] = ACTIONS(1),
    [sym__raw_html_comment] = ACTIONS(1),
    [sym__sc_comment_body] = ACTIONS(1),
    [sym__error_sentinel] = ACTIONS(1),
    [sym__raw_passage_body] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(66),
    [sym_passage] = STATE(39),
    [sym_passage_header] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(32),
    [aux_sym_source_file_repeat2] = STATE(33),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_source_file_token1] = ACTIONS(5),
    [anon_sym_COLON_COLON] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      anon_sym_COLON_COLON,
    ACTIONS(15), 1,
      anon_sym_LT_LT,
    ACTIONS(17), 1,
      anon_sym_LT_LT_SLASH,
    ACTIONS(19), 1,
      anon_sym_LT_LTscript_GT_GT,
    ACTIONS(21), 1,
      anon_sym_AT_AT,
    ACTIONS(23), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACKimg_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LT_LT_EQ,
    ACTIONS(29), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(31), 1,
      anon_sym_LT_BANG_DASH_DASH,
    STATE(40), 1,
      sym_passage_body,
    ACTIONS(11), 9,
      aux_sym_source_file_token1,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      sym_variable,
      sym_temp_variable,
      sym_text,
    STATE(4), 11,
      sym__passage_content,
      sym_macro,
      sym_end_macro,
      sym_script_block,
      sym_styled_text,
      sym_wiki_link,
      sym_image_link,
      sym_naked_expression,
      sym_sc_comment,
      sym_html_comment,
      aux_sym_passage_body_repeat1,
  [61] = 13,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      anon_sym_COLON_COLON,
    ACTIONS(40), 1,
      anon_sym_LT_LT,
    ACTIONS(43), 1,
      anon_sym_LT_LT_SLASH,
    ACTIONS(46), 1,
      anon_sym_LT_LTscript_GT_GT,
    ACTIONS(49), 1,
      anon_sym_AT_AT,
    ACTIONS(52), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(55), 1,
      anon_sym_LBRACKimg_LBRACK,
    ACTIONS(58), 1,
      anon_sym_LT_LT_EQ,
    ACTIONS(61), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(64), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(35), 9,
      aux_sym_source_file_token1,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      sym_variable,
      sym_temp_variable,
      sym_text,
    STATE(3), 11,
      sym__passage_content,
      sym_macro,
      sym_end_macro,
      sym_script_block,
      sym_styled_text,
      sym_wiki_link,
      sym_image_link,
      sym_naked_expression,
      sym_sc_comment,
      sym_html_comment,
      aux_sym_passage_body_repeat1,
  [119] = 13,
    ACTIONS(15), 1,
      anon_sym_LT_LT,
    ACTIONS(17), 1,
      anon_sym_LT_LT_SLASH,
    ACTIONS(19), 1,
      anon_sym_LT_LTscript_GT_GT,
    ACTIONS(21), 1,
      anon_sym_AT_AT,
    ACTIONS(23), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACKimg_LBRACK,
    ACTIONS(27), 1,
      anon_sym_LT_LT_EQ,
    ACTIONS(29), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(31), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      anon_sym_COLON_COLON,
    ACTIONS(69), 9,
      aux_sym_source_file_token1,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      sym_variable,
      sym_temp_variable,
      sym_text,
    STATE(3), 11,
      sym__passage_content,
      sym_macro,
      sym_end_macro,
      sym_script_block,
      sym_styled_text,
      sym_wiki_link,
      sym_image_link,
      sym_naked_expression,
      sym_sc_comment,
      sym_html_comment,
      aux_sym_passage_body_repeat1,
  [177] = 10,
    ACTIONS(75), 1,
      anon_sym_GT_GT,
    ACTIONS(77), 1,
      aux_sym__macro_arg_token_token6,
    ACTIONS(79), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      anon_sym_SQUOTE,
    ACTIONS(83), 1,
      anon_sym_BQUOTE,
    ACTIONS(87), 1,
      anon_sym_LT_LT_EQ,
    STATE(55), 1,
      sym_macro_args,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(6), 5,
      sym__macro_arg_token,
      sym_string_literal,
      sym_bool_literal,
      sym_naked_expression,
      aux_sym_macro_args_repeat1,
    ACTIONS(73), 10,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__macro_arg_token_token1,
      aux_sym__macro_arg_token_token2,
      aux_sym__macro_arg_token_token3,
      aux_sym__macro_arg_token_token4,
      aux_sym__macro_arg_token_token5,
      sym_variable,
      sym_temp_variable,
      sym_number_literal,
  [222] = 9,
    ACTIONS(79), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      anon_sym_SQUOTE,
    ACTIONS(83), 1,
      anon_sym_BQUOTE,
    ACTIONS(87), 1,
      anon_sym_LT_LT_EQ,
    ACTIONS(91), 1,
      anon_sym_GT_GT,
    ACTIONS(93), 1,
      aux_sym__macro_arg_token_token6,
    ACTIONS(85), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 5,
      sym__macro_arg_token,
      sym_string_literal,
      sym_bool_literal,
      sym_naked_expression,
      aux_sym_macro_args_repeat1,
    ACTIONS(89), 10,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__macro_arg_token_token1,
      aux_sym__macro_arg_token_token2,
      aux_sym__macro_arg_token_token3,
      aux_sym__macro_arg_token_token4,
      aux_sym__macro_arg_token_token5,
      sym_variable,
      sym_temp_variable,
      sym_number_literal,
  [264] = 9,
    ACTIONS(98), 1,
      anon_sym_GT_GT,
    ACTIONS(100), 1,
      aux_sym__macro_arg_token_token6,
    ACTIONS(103), 1,
      anon_sym_DQUOTE,
    ACTIONS(106), 1,
      anon_sym_SQUOTE,
    ACTIONS(109), 1,
      anon_sym_BQUOTE,
    ACTIONS(115), 1,
      anon_sym_LT_LT_EQ,
    ACTIONS(112), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 5,
      sym__macro_arg_token,
      sym_string_literal,
      sym_bool_literal,
      sym_naked_expression,
      aux_sym_macro_args_repeat1,
    ACTIONS(95), 10,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__macro_arg_token_token1,
      aux_sym__macro_arg_token_token2,
      aux_sym__macro_arg_token_token3,
      aux_sym__macro_arg_token_token4,
      aux_sym__macro_arg_token_token5,
      sym_variable,
      sym_temp_variable,
      sym_number_literal,
  [306] = 3,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    ACTIONS(120), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [334] = 2,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [359] = 2,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    ACTIONS(130), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [384] = 2,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
    ACTIONS(134), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [409] = 2,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [434] = 2,
    ACTIONS(140), 1,
      ts_builtin_sym_end,
    ACTIONS(142), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [459] = 2,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
    ACTIONS(146), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [484] = 2,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
    ACTIONS(150), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [509] = 2,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
    ACTIONS(154), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [534] = 2,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [559] = 2,
    ACTIONS(160), 1,
      ts_builtin_sym_end,
    ACTIONS(162), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [584] = 2,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
    ACTIONS(166), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [609] = 2,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
    ACTIONS(170), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [634] = 2,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    ACTIONS(174), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [659] = 2,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
    ACTIONS(178), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [684] = 2,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [709] = 2,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
    ACTIONS(186), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [734] = 2,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
    ACTIONS(190), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [759] = 2,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
    ACTIONS(194), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [784] = 2,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
    ACTIONS(198), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [809] = 2,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
    ACTIONS(202), 19,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      aux_sym__passage_content_token3,
      aux_sym__passage_content_token4,
      sym_html_tag,
      anon_sym_LT_LT,
      anon_sym_LT_LT_SLASH,
      anon_sym_LT_LTscript_GT_GT,
      sym_variable,
      sym_temp_variable,
      anon_sym_AT_AT,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT_EQ,
      anon_sym_SLASH_STAR,
      anon_sym_LT_BANG_DASH_DASH,
      sym_text,
  [834] = 2,
    ACTIONS(206), 1,
      aux_sym__macro_arg_token_token6,
    ACTIONS(204), 17,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      anon_sym_GT_GT,
      aux_sym__macro_arg_token_token1,
      aux_sym__macro_arg_token_token2,
      aux_sym__macro_arg_token_token3,
      aux_sym__macro_arg_token_token4,
      aux_sym__macro_arg_token_token5,
      sym_variable,
      sym_temp_variable,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LT_LT_EQ,
  [857] = 2,
    ACTIONS(210), 1,
      aux_sym__macro_arg_token_token6,
    ACTIONS(208), 17,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      anon_sym_GT_GT,
      aux_sym__macro_arg_token_token1,
      aux_sym__macro_arg_token_token2,
      aux_sym__macro_arg_token_token3,
      aux_sym__macro_arg_token_token4,
      aux_sym__macro_arg_token_token5,
      sym_variable,
      sym_temp_variable,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LT_LT_EQ,
  [880] = 2,
    ACTIONS(164), 1,
      aux_sym__macro_arg_token_token6,
    ACTIONS(166), 17,
      aux_sym__passage_content_token1,
      aux_sym__passage_content_token2,
      anon_sym_GT_GT,
      aux_sym__macro_arg_token_token1,
      aux_sym__macro_arg_token_token2,
      aux_sym__macro_arg_token_token3,
      aux_sym__macro_arg_token_token4,
      aux_sym__macro_arg_token_token5,
      sym_variable,
      sym_temp_variable,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_number_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LT_LT_EQ,
  [903] = 7,
    ACTIONS(7), 1,
      anon_sym_COLON_COLON,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
    ACTIONS(214), 1,
      aux_sym_source_file_token1,
    STATE(2), 1,
      sym_passage_header,
    STATE(36), 1,
      aux_sym_source_file_repeat2,
    STATE(37), 1,
      aux_sym_source_file_repeat1,
    STATE(39), 1,
      sym_passage,
  [925] = 5,
    ACTIONS(7), 1,
      anon_sym_COLON_COLON,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_passage_header,
    STATE(35), 1,
      aux_sym_source_file_repeat2,
    STATE(39), 1,
      sym_passage,
  [941] = 5,
    ACTIONS(216), 1,
      aux_sym_passage_header_token1,
    ACTIONS(218), 1,
      anon_sym_LBRACK,
    ACTIONS(220), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_tag_list,
    STATE(76), 1,
      sym_metadata,
  [957] = 5,
    ACTIONS(222), 1,
      ts_builtin_sym_end,
    ACTIONS(224), 1,
      anon_sym_COLON_COLON,
    STATE(2), 1,
      sym_passage_header,
    STATE(35), 1,
      aux_sym_source_file_repeat2,
    STATE(39), 1,
      sym_passage,
  [973] = 5,
    ACTIONS(7), 1,
      anon_sym_COLON_COLON,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_passage_header,
    STATE(35), 1,
      aux_sym_source_file_repeat2,
    STATE(39), 1,
      sym_passage,
  [989] = 3,
    ACTIONS(231), 1,
      aux_sym_source_file_token1,
    STATE(37), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(229), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [1000] = 3,
    ACTIONS(214), 1,
      aux_sym_source_file_token1,
    STATE(37), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(222), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [1011] = 3,
    ACTIONS(236), 1,
      aux_sym_source_file_token1,
    STATE(38), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(234), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [1022] = 1,
    ACTIONS(238), 3,
      ts_builtin_sym_end,
      aux_sym_source_file_token1,
      anon_sym_COLON_COLON,
  [1028] = 3,
    ACTIONS(240), 1,
      anon_sym_RBRACK,
    ACTIONS(242), 1,
      sym_tag,
    STATE(42), 1,
      aux_sym_tag_list_repeat1,
  [1038] = 3,
    ACTIONS(244), 1,
      anon_sym_RBRACK,
    ACTIONS(246), 1,
      sym_tag,
    STATE(42), 1,
      aux_sym_tag_list_repeat1,
  [1048] = 3,
    ACTIONS(249), 1,
      anon_sym_RBRACK,
    ACTIONS(251), 1,
      sym_tag,
    STATE(41), 1,
      aux_sym_tag_list_repeat1,
  [1058] = 3,
    ACTIONS(220), 1,
      anon_sym_LBRACE,
    ACTIONS(253), 1,
      aux_sym_passage_header_token1,
    STATE(58), 1,
      sym_metadata,
  [1068] = 2,
    ACTIONS(255), 1,
      anon_sym_STAR_SLASH,
    ACTIONS(257), 1,
      sym__sc_comment_body,
  [1075] = 2,
    ACTIONS(259), 1,
      anon_sym_LT_LT_SLASHscript_GT_GT,
    ACTIONS(261), 1,
      sym__raw_js_body,
  [1082] = 2,
    ACTIONS(263), 1,
      aux_sym_styled_text_token1,
    ACTIONS(265), 1,
      aux_sym_styled_text_token2,
  [1089] = 2,
    ACTIONS(267), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(269), 1,
      sym__raw_html_comment,
  [1096] = 2,
    ACTIONS(271), 1,
      anon_sym_PIPE,
    ACTIONS(273), 1,
      anon_sym_RBRACK_RBRACK,
  [1103] = 1,
    ACTIONS(275), 2,
      aux_sym_passage_header_token1,
      anon_sym_LBRACE,
  [1108] = 2,
    ACTIONS(277), 1,
      anon_sym_end,
    ACTIONS(279), 1,
      sym_macro_name,
  [1115] = 1,
    ACTIONS(281), 2,
      aux_sym_passage_header_token1,
      anon_sym_LBRACE,
  [1120] = 1,
    ACTIONS(283), 1,
      anon_sym_DASH_DASH_GT,
  [1124] = 1,
    ACTIONS(285), 1,
      aux_sym_image_link_token1,
  [1128] = 1,
    ACTIONS(287), 1,
      anon_sym_GT_GT,
  [1132] = 1,
    ACTIONS(289), 1,
      aux_sym_naked_expression_token1,
  [1136] = 1,
    ACTIONS(291), 1,
      anon_sym_SEMI,
  [1140] = 1,
    ACTIONS(293), 1,
      aux_sym_passage_header_token1,
  [1144] = 1,
    ACTIONS(295), 1,
      aux_sym_styled_text_token2,
  [1148] = 1,
    ACTIONS(297), 1,
      anon_sym_GT_GT,
  [1152] = 1,
    ACTIONS(299), 1,
      sym_link_text,
  [1156] = 1,
    ACTIONS(301), 1,
      sym_passage_name,
  [1160] = 1,
    ACTIONS(303), 1,
      anon_sym_STAR_SLASH,
  [1164] = 1,
    ACTIONS(305), 1,
      anon_sym_GT_GT,
  [1168] = 1,
    ACTIONS(307), 1,
      anon_sym_AT_AT,
  [1172] = 1,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
  [1176] = 1,
    ACTIONS(311), 1,
      sym_link_text,
  [1180] = 1,
    ACTIONS(313), 1,
      aux_sym_string_literal_token1,
  [1184] = 1,
    ACTIONS(315), 1,
      aux_sym_string_literal_token3,
  [1188] = 1,
    ACTIONS(317), 1,
      sym_macro_name,
  [1192] = 1,
    ACTIONS(319), 1,
      aux_sym_metadata_token1,
  [1196] = 1,
    ACTIONS(321), 1,
      anon_sym_DQUOTE,
  [1200] = 1,
    ACTIONS(321), 1,
      anon_sym_SQUOTE,
  [1204] = 1,
    ACTIONS(321), 1,
      anon_sym_BQUOTE,
  [1208] = 1,
    ACTIONS(323), 1,
      aux_sym_string_literal_token2,
  [1212] = 1,
    ACTIONS(325), 1,
      aux_sym_passage_header_token1,
  [1216] = 1,
    ACTIONS(327), 1,
      anon_sym_AT_AT,
  [1220] = 1,
    ACTIONS(329), 1,
      anon_sym_RBRACK_RBRACK,
  [1224] = 1,
    ACTIONS(331), 1,
      sym_link_text,
  [1228] = 1,
    ACTIONS(333), 1,
      sym_macro_name,
  [1232] = 1,
    ACTIONS(335), 1,
      anon_sym_RBRACK_RBRACK,
  [1236] = 1,
    ACTIONS(337), 1,
      anon_sym_GT_GT,
  [1240] = 1,
    ACTIONS(339), 1,
      anon_sym_RBRACK,
  [1244] = 1,
    ACTIONS(341), 1,
      anon_sym_LT_LT_SLASHscript_GT_GT,
  [1248] = 1,
    ACTIONS(343), 1,
      anon_sym_RBRACE,
  [1252] = 1,
    ACTIONS(345), 1,
      anon_sym_GT_GT,
  [1256] = 1,
    ACTIONS(347), 1,
      aux_sym_naked_expression_token1,
  [1260] = 1,
    ACTIONS(349), 1,
      aux_sym_passage_header_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 61,
  [SMALL_STATE(4)] = 119,
  [SMALL_STATE(5)] = 177,
  [SMALL_STATE(6)] = 222,
  [SMALL_STATE(7)] = 264,
  [SMALL_STATE(8)] = 306,
  [SMALL_STATE(9)] = 334,
  [SMALL_STATE(10)] = 359,
  [SMALL_STATE(11)] = 384,
  [SMALL_STATE(12)] = 409,
  [SMALL_STATE(13)] = 434,
  [SMALL_STATE(14)] = 459,
  [SMALL_STATE(15)] = 484,
  [SMALL_STATE(16)] = 509,
  [SMALL_STATE(17)] = 534,
  [SMALL_STATE(18)] = 559,
  [SMALL_STATE(19)] = 584,
  [SMALL_STATE(20)] = 609,
  [SMALL_STATE(21)] = 634,
  [SMALL_STATE(22)] = 659,
  [SMALL_STATE(23)] = 684,
  [SMALL_STATE(24)] = 709,
  [SMALL_STATE(25)] = 734,
  [SMALL_STATE(26)] = 759,
  [SMALL_STATE(27)] = 784,
  [SMALL_STATE(28)] = 809,
  [SMALL_STATE(29)] = 834,
  [SMALL_STATE(30)] = 857,
  [SMALL_STATE(31)] = 880,
  [SMALL_STATE(32)] = 903,
  [SMALL_STATE(33)] = 925,
  [SMALL_STATE(34)] = 941,
  [SMALL_STATE(35)] = 957,
  [SMALL_STATE(36)] = 973,
  [SMALL_STATE(37)] = 989,
  [SMALL_STATE(38)] = 1000,
  [SMALL_STATE(39)] = 1011,
  [SMALL_STATE(40)] = 1022,
  [SMALL_STATE(41)] = 1028,
  [SMALL_STATE(42)] = 1038,
  [SMALL_STATE(43)] = 1048,
  [SMALL_STATE(44)] = 1058,
  [SMALL_STATE(45)] = 1068,
  [SMALL_STATE(46)] = 1075,
  [SMALL_STATE(47)] = 1082,
  [SMALL_STATE(48)] = 1089,
  [SMALL_STATE(49)] = 1096,
  [SMALL_STATE(50)] = 1103,
  [SMALL_STATE(51)] = 1108,
  [SMALL_STATE(52)] = 1115,
  [SMALL_STATE(53)] = 1120,
  [SMALL_STATE(54)] = 1124,
  [SMALL_STATE(55)] = 1128,
  [SMALL_STATE(56)] = 1132,
  [SMALL_STATE(57)] = 1136,
  [SMALL_STATE(58)] = 1140,
  [SMALL_STATE(59)] = 1144,
  [SMALL_STATE(60)] = 1148,
  [SMALL_STATE(61)] = 1152,
  [SMALL_STATE(62)] = 1156,
  [SMALL_STATE(63)] = 1160,
  [SMALL_STATE(64)] = 1164,
  [SMALL_STATE(65)] = 1168,
  [SMALL_STATE(66)] = 1172,
  [SMALL_STATE(67)] = 1176,
  [SMALL_STATE(68)] = 1180,
  [SMALL_STATE(69)] = 1184,
  [SMALL_STATE(70)] = 1188,
  [SMALL_STATE(71)] = 1192,
  [SMALL_STATE(72)] = 1196,
  [SMALL_STATE(73)] = 1200,
  [SMALL_STATE(74)] = 1204,
  [SMALL_STATE(75)] = 1208,
  [SMALL_STATE(76)] = 1212,
  [SMALL_STATE(77)] = 1216,
  [SMALL_STATE(78)] = 1220,
  [SMALL_STATE(79)] = 1224,
  [SMALL_STATE(80)] = 1228,
  [SMALL_STATE(81)] = 1232,
  [SMALL_STATE(82)] = 1236,
  [SMALL_STATE(83)] = 1240,
  [SMALL_STATE(84)] = 1244,
  [SMALL_STATE(85)] = 1248,
  [SMALL_STATE(86)] = 1252,
  [SMALL_STATE(87)] = 1256,
  [SMALL_STATE(88)] = 1260,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_passage_body_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_body, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_body, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_args, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_args_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_args_repeat1, 2, 0, 0),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_args_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_args_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_args_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_args_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_args_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_args_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image_link, 3, 0, 7),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image_link, 3, 0, 7),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_macro, 3, 0, 1),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_macro, 3, 0, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_header, 3, 0, 1),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_header, 3, 0, 1),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_header, 4, 0, 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_header, 4, 0, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_header, 4, 0, 3),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_header, 4, 0, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 3, 0, 1),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 3, 0, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_styled_text, 3, 0, 5),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_styled_text, 3, 0, 5),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_block, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_block, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_block, 3, 0, 4),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_block, 3, 0, 4),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wiki_link, 3, 0, 6),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wiki_link, 3, 0, 6),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sc_comment, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sc_comment, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_naked_expression, 3, 0, 8),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_naked_expression, 3, 0, 8),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sc_comment, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sc_comment, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_comment, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_comment, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage_header, 5, 0, 9),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_passage_header, 5, 0, 9),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_macro, 4, 0, 10),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_macro, 4, 0, 10),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 4, 0, 11),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 4, 0, 11),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_comment, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_comment, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_styled_text, 5, 0, 12),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_styled_text, 5, 0, 12),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wiki_link, 5, 0, 13),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wiki_link, 5, 0, 13),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image_link, 6, 0, 14),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image_link, 6, 0, 14),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool_literal, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool_literal, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(62),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0),
  [246] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_list_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_list, 3, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_list, 2, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [309] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata, 3, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__raw_js_body = 0,
  ts_external_token__raw_html_comment = 1,
  ts_external_token__sc_comment_body = 2,
  ts_external_token__error_sentinel = 3,
  ts_external_token__raw_passage_body = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__raw_js_body] = sym__raw_js_body,
  [ts_external_token__raw_html_comment] = sym__raw_html_comment,
  [ts_external_token__sc_comment_body] = sym__sc_comment_body,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
  [ts_external_token__raw_passage_body] = sym__raw_passage_body,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__raw_js_body] = true,
    [ts_external_token__raw_html_comment] = true,
    [ts_external_token__sc_comment_body] = true,
    [ts_external_token__error_sentinel] = true,
    [ts_external_token__raw_passage_body] = true,
  },
  [2] = {
    [ts_external_token__sc_comment_body] = true,
  },
  [3] = {
    [ts_external_token__raw_js_body] = true,
  },
  [4] = {
    [ts_external_token__raw_html_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sugarcube_external_scanner_create(void);
void tree_sitter_sugarcube_external_scanner_destroy(void *);
bool tree_sitter_sugarcube_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sugarcube_external_scanner_serialize(void *, char *);
void tree_sitter_sugarcube_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sugarcube(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sugarcube_external_scanner_create,
      tree_sitter_sugarcube_external_scanner_destroy,
      tree_sitter_sugarcube_external_scanner_scan,
      tree_sitter_sugarcube_external_scanner_serialize,
      tree_sitter_sugarcube_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "sugarcube",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
